version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://ngkien1911:CJ5TRhBBUXe95Qwa@monolisarose.lhhzqgz.mongodb.net/?retryWrites=true&w=majority&appName=MonolisaRose
      - JWT_SECRET=Hfj8aP1Kx7Dq2MvZ3Nw5YrT9LcGbJQ0VoXU6RzAmC4EoKdBYWlFtpS8MZnHiOJeh
    depends_on:
      - mongodb

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=foodordering
      - DB_USERNAME=ngkien1911
      - DB_PASSWORD=KienNguyen@1911
    depends_on:
      - mysql

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/foodordering
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=KienNguyen@1911
    depends_on:
      - postgres

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/foodordering
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=KienNguyen@1911
    depends_on:
      - postgres

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=foodordering
      - MYSQL_ROOT_PASSWORD=KienNguyen@1911
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=foodordering
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=KienNguyen@1911
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  mysql_data:
  postgres_data: 